language: python
python: 3.4

env:
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=docs

before_install:
  - sudo apt-get install make

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
