language: python
python: 3.4

env:
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34

install:
  - case ${TOX_ENV} in
      py32) pip install virtualenv\<14 --upgrade;;
      *) pip install virtualenv --upgrade;;
    esac
  - pip install tox

script:
  - tox -e $TOX_ENV
